<?php
/**
 * Generated by universal php auto loader
 * @link http://github.com/dmkuznetsov/php-autoloader
 * @copyright Copyright (c) 2012-2013 Dmitry Kuznetsov <kuznetsov2d@gmail.com>
 * @license http://raw.github.com/dmkuznetsov/php-autoloader/master/LICENSE.txt New BSD License
 * @date
 */
function __dm_autoload( $name )
{
	$map = array();
	if ( isset( $map[ $name ] ) )
	{
		require $map[ $name ];
	}
}
spl_autoload_register( '__dm_autoload' );
